import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/Navbar";
import ClientProviders from "@/components/ClientProviders";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={geistSans.variable}>
       <body className={`${geistMono.variable} font-sans`}>
        {/* <SessionProvider> */}
          <ClientProviders>
            <Navbar />
            {children}
            <Footer />
          </ClientProviders>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
